### ISSUE TITLE
Could someone write simple instructions on how to install this. Or make a video?

### ISSUE THREAD

**Issue by polorsport** [fusionjack/Adhell3#9]
Myself, and many others would love to use this program.

But, can't follow the instructions. As we simply don't know how to: "Set applicationId with a valid package name in app\build.gradle, e.g.: com.dhf.erz58384". 

Maybe an explain it like I'm five guide.

Thanks for your work, and effort on this project.

**Comment by Mike-BITW** [comment]
It's not easy to make it any simpler than it already is.  Let's pretend that you're a 5-year old who can read (I'm not good at drawing pictures):

(1) Open your copy of the AdHell3 project in Android Studio, 
(2) find the "app/build.gradle" script (use backslash if you use the thing from Microsoft, proper slash if you have a civilized OS), 
 3) find the line that says **applicationId "com."** and change the "_com._" part to your unique package ID, so that it ends up reading **applicationId "com.something.1234"** or whatever you pick, 
(4) follow the rest of the instructions to compile your very own AdHell3 version.

**Comment by polorsport** [comment]
Thanks for getting back to me. 

1.. After I change it to ""com.something.1234" do I click save and close Android stuido?

2. For the next step. I don't know what to do either.

"Update the source code with git pull --rebase or re-download the source code as a zip file"

Is it referring to hitting the green button clone/download button on this page?(https://github.com/fusionjack/Adhell3P)

3. Can I run a windows powershell from inside the extracted folder Adhell3-master\Adhell3-master\app

than run

Run these following commands in a console: 
cd adhell3
gradlew clean assembleDebug

**Comment by Mike-BITW** [comment]
I thought you were only confused about the renaming step.  If you re-downloaded the source **after** you already changed it locally, it would be silly at best.  If your Android Studio is installed correctly and you opened the AdHell3 project correctly, you should be able to directly compile from there. Powershell?  That's a W*ndows thing (is it your shell/console prompt??)  that I know nothing about. 

Based on your questions, there's a strong possibility that AdHell3 might not be the right solution for you. I'm afraid I don't know you well enough to hold your hand for this long, so I'll step back and let @fusionjack answer you. If all else fails, consider Samsung's Disconnect Pro or one of the many VPN-based apps that are readily available. Sorry I couldn't help you.

**Comment by herexf** [comment]
Just in case, there is 2 links you get the code, sometimes SSH doesn't work, you can try HPPTS one.
```
SSH    git@github.com:fusionjack/Adhell3.git
HTTPS  https://github.com/fusionjack/Adhell3.git
```

I'm giving you a another way for updating the latest codes and rebuild the apk.
If you don't know how to use the scripts.

**Download the latest commit manually.**

Every time you will see the latest commit by Jack when you access this project:
`https://github.com/fusionjack/Adhell3`

Check the first line:
`fusionjack Rework mobile restricter  …     Latest commit e343438  3 hours ago`

Then click the "e343438"
You will be directed to below link
[https://github.com/fusionjack/Adhell3/commit/e3434382cd10d83ce0c8f91dbae73aa1a03d3e57](https://github.com/fusionjack/Adhell3/commit/e3434382cd10d83ce0c8f91dbae73aa1a03d3e57)

Click Browse file, then "Clone or download", choose download zip.
Unzip and copy to your project folder.

Open Android Studio, will open you recent project automatically, go to Gradle Scripts /build.gradle(module:app)
Find applicationId, change com. to your name like com.someone.appname

**Comment by polorsport** [comment]
I followed everything stated. Unfortunately the Build APK is not working. 

I see a message below that says: "Grade sync failed: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME [environment] variable."

screen shot:

https://i.imgur.com/YQKjE6F.png

**Comment by herexf** [comment]
You need install SDK version 26

Go to menu
File -> Settings -> Appearance & Behavior -> system settings -> Android SDK

You also can find the installed SDK location here.

Please ensure you have already installed Android 8.0 Oreo SDK, will be better if you stall all above versions, from 8.0 to P

Thanks

**Comment by fxsoap** [comment]
@polorsport I had the same issue. I've never used Android studio and i've been trying to read guides on how to take the files after renaming the com.x.etc and I get as far as "Run--build APK" but got stopped there with issues

**Comment by fusionjack** [comment]
installing android studio is easy peasy :relaxed:
* just run the installer and click next, next next and let it download the stuff for you.
* after then, open the adhell3 project and wait a little bit until it is built.
* you will then see error messages to install sdk 26 and then build tool 26.0.2. just click on them.
* after finish downloading them, set the package name change "com." to something else
* build the apk or run it (green play icon) so that it will be installed automatically into your phone

**Comment by Mike-BITW** [comment]
You're a very patient man!  

You forgot a few tricky steps, such as:
- turn on computer
- open eyes
- locate keyboard
- read screen
- etc...

;)

**Comment by polorsport** [comment]
I uninstalled Android studio, ran ccleaner. Then reinstalled it, while installing SDK platforms Android 8.0, and Android P Preview. (SDK version 26 was already installed apparatnly)

I now don't see any errors when I launch Android Studio.

However when I Menu Build.  

There is no "Build APK(s)" option. As @herexf stated

The options are:

Make Module
Generate signed APK
Analyse APK
Deploy Module to App engine

I tried to "Make Module" and received this error below

I don't know how to proceed.


Error:Android Source Generator: Error: Can't find bundle for base name messages.AndroidJpsBundle, locale en_US
java.util.MissingResourceException: Can't find bundle for base name messages.AndroidJpsBundle, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.jetbrains.jps.android.AndroidJpsBundle.getBundle(AndroidJpsBundle.java:22)
	at org.jetbrains.jps.android.AndroidJpsBundle.message(AndroidJpsBundle.java:32)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.computeModuleDatas(AndroidSourceGeneratingBuilder.java:1276)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.doBuild(AndroidSourceGeneratingBuilder.java:130)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.build(AndroidSourceGeneratingBuilder.java:114)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1246)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:923)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:995)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:886)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:719)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:371)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:308)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:138)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:235)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by oreomanfan** [comment]
When making the project, it fails and appears to be missing a bunch of things from the knox sdk? I'm unsure how to import that into the project.

error: package com.sec.enterprise does not exist |  
error: package com.sec.enterprise.firewall does not exist |  
error: package com.sec.enterprise.firewall does not exist |

**Comment by herexf** [comment]
@oreomanfan

Download SAMSUNG KNOX STD SDK, 
Samsung-Knox-Standard-SDK-v5_9-(20170828).zip
Put to app/libs

3 files

**Comment by scooterusa** [comment]
Adding in case if it helps - On April 4th one of the changes made was the removal of the SDK. It was commented that the file could be downloaded and a link provided. 

So as stated above when you extract the files you will find a folder called libs in the SDK. Copy and paste that folder into the app folder within the adhell3 zip file you will have downloaded. As always make sure you do the required change in the build.gradle and you should be able to build the APK without issue.

Just be sure to keep the downloaded Knox SDK handy so you can copy the libs folder (or any other files from the SDK) as needed.

**Comment by herexf** [comment]
@oreomanfan 

Yes, not Knox SDK, it's Knox Standard SDK v5.9, :)

**Comment by binoandroid** [comment]
> @oreomanfan
> 
> Download SAMSUNG KNOX STD SDK, https://seap.samsung.com/sdk/knox-standard-android
> Samsung-Knox-Standard-SDK-v5_9-(20170828).zip
> Put to app/libs
> 
> 3 files

Thanks, excuse my ignorance it was 2 days since I could no longer create the apk.
you have to put this note in the file:  **README.md**

**Comment by fusionjack** [comment]
i plan to move to gitlab and rework the README.md. that's why i didn't update it yet.
